# Generated by Django 5.1.2 on 2024-10-30 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_address", models.CharField(max_length=300)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("W", "Windsor"),
                            ("T", "Toronto"),
                            ("L", "Waterloo"),
                            ("C", "Chatham"),
                        ],
                        default="W",
                        max_length=2,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interested_in",
                    models.ManyToManyField(blank=True, to="carapp.cartype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=200)),
                ("car_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.PositiveIntegerField(default=0)),
                ("instock", models.BooleanField(default=True)),
                (
                    "car_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="carapp.cartype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Cancelled"),
                            (1, "Placed"),
                            (2, "Shipped"),
                            (3, "Delivered"),
                        ],
                        default=1,
                    ),
                ),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carapp.buyer"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carapp.vehicle"
                    ),
                ),
            ],
        ),
    ]
