# Generated by Django 5.1.2 on 2024-11-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("semester", models.PositiveIntegerField()),
                ("personal_link", models.URLField()),
            ],
            options={
                "ordering": ["first_name"],
            },
        ),
    ]
