# Generated by Django 5.1.2 on 2024-11-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0002_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="features",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Cruise Control"),
                    ("AI", "Audio Interface"),
                    ("AB", "Airbags"),
                    ("AC", "Air Conditioning"),
                    ("SH", "Seat Heating"),
                    ("PA", "ParkAssist"),
                    ("PS", "Power Steering"),
                    ("RC", "Reversing Camera"),
                    ("AS", "Auto Start/Stop"),
                ],
                max_length=255,
            ),
        ),
    ]
